name: Deploy SDK

on:
  release:
    types:
      - published

jobs:
  deploy_pre_release:
    name: Deploy Client Pre-Release to PYPI
    if: ${{ github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Check Release Tag Format
        run: |
          re=[0-9]+\.[0-9]+\.[0-9]+b[0-9]+
          if ! [[ $RELEASE_VERSION =~ $re ]]; then
            echo 'Tag does not match expected regex pattern for beta releases (v[0-9]+.[0-9]+.[0-9]+b[0-9]+)'
            echo $RELEASE_VERSION
            echo 'Please update your tag to match the expected regex pattern'
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/openapi-generator-sdk

      - name: Install Packages
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test
        run: |
          pytest -v

      - name: Deploy to PYPI
        run: |
          pip install twine
          pip install wheel
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p $PYPI_API_KEY
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          
      - uses: Bandwidth/build-notify-slack-action@v2.0.0
        if: always()
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}

  deploy:
    name: Deploy `main` to PYPI
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Check Release Tag Format
        run: |
          re=[0-9]+\.[0-9]+\.[0-9]+
          if ! [[ $RELEASE_VERSION =~ $re ]]; then
            echo 'Tag does not match expected regex pattern for beta releases (v[0-9]+.[0-9]+.[0-9]+b[0-9]+)'
            echo $RELEASE_VERSION
            echo 'Please update your tag to match the expected regex pattern'
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: |-
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test
        run: |-
          pytest -v

      - name: Deploy to PYPI
        run: |
          pip install twine
          pip install wheel
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p $PYPI_API_KEY
        env:
          PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}

      - uses: Bandwidth/build-notify-slack-action@v2.0.0
        if: always()
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
